stages:
  - build

build:
  stage: build
  artifacts:
    untracked: true
  image:
    name: gcr.io/kaniko-project/executor:v1.10.0-debug
    entrypoint: [""]
  script:
    - /kaniko/executor
      --context "${CI_PROJECT_DIR}"
      --dockerfile "${CI_PROJECT_DIR}/Dockerfile"
      --no-push
      --destination tar
      --tar-path "${CI_PROJECT_TITLE}".tar
