stages:
  - build
  - push

build:
  stage: build
  artifacts:
    untracked: true
  image:
    name: gcr.io/kaniko-project/executor:v1.10.0-debug
    entrypoint: [""]
  script:
    - /kaniko/executor
      --context "${CI_PROJECT_DIR}"
      --dockerfile "${CI_PROJECT_DIR}/Dockerfile"
      --no-push
      --destination tar
      --tar-path "${CI_PROJECT_TITLE}.tar"

push-to-harbor:
  stage: push 
  image:
    name: gcr.io/go-containerregistry/crane:debug
    entrypoint: [""]
  dependencies:
    - build
  script:
    - crane auth login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - crane push "${CI_PROJECT_TITLE}.tar" "${CI_REGISTRY}/${CI_PROJECT_TITLE}.tar:${CI_COMMIT_SHORT_SHA}"
    - crane push "${CI_PROJECT_TITLE}.tar" "${CI_REGISTRY}/${CI_PROJECT_TITLE}.tar:latest"
