---
version: "3.9"
services:
  pxls-backend:
    build:
      dockerfile: Dockerfile
      context: .
    restart: always
    ports:
      - "4567:4567"
    environment:
      DATABASE_USER: "pxls"
      DATABASE_PASSWORD: "ChAnGeMeAtYoUrEaRlIeStCoNvEnIeNcE"
      DATABASE_NAME: "pxls"
      DATABASE_HOST: "pxls-database"
      PXLS_HOST: "localhost"
    volumes:
      - pxls-datastore:/data
  
  pxls-frontend:
    build:
      dockerfile: DockerfileFront
      context: .
    restart: always
    ports:
      - "8080:3000"

  pxls-database:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: "pxls"
      POSTGRES_PASSWORD: "ChAnGeMeAtYoUrEaRlIeStCoNvEnIeNcE"
      POSTGRES_DB: "pxls"
    command: postgres -c 'max_connections=1000'
    volumes:
      - pxls-database:/var/lib/postgresql

volumes:
  pxls-database: {}
  pxls-datastore: {}
