---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pxls-app
  namespace: pxls
spec:
  selector:
    matchLabels:
      app: "pxls"
      tier: "frontend"
      environment: "testing"
  replicas: 1
  template:
    metadata:
      namespace: "pxls-test"
      labels:
        app: "pxls"
        tier: "frontend"
        environment: "testing"
    spec:
      terminationGracePeriodSeconds: 30
      containers:
        - name: "pxls"
          image: "pxls/pxls:develop"
          env:
            - name: "DATABASE_USER"
              value: 'pxls"
            - name: "DATABASE_PASSWORD"
              value: "ChAnGeMeAtYoUrEaRlIeStCoNvEnIeNcE"
            - name: "DATABASE_NAME"
              value: "pxls"
            - name: "DATABASE_HOST"
              value: "postgres-test"
            - name: "PXLS_HOST"
              value: "0.0.0.0"
          ports:
            - containerPort: 4567
              name: "pxls-console"
