version: "3"
services:
  pxls-frontend:
    image: m08y/docker-pxls-space:latest
    restart: always
    ports:
      - "4567"
    environment:
      DATABASE_USER: "pxls"
      DATABASE_PASSWORD: "ChAnGeMeAtYoUrEaRlIeStCoNvEnIeNcE"
      DATABASE_NAME: "pxls"
      DATABASE_HOST: "pxls-database"
      PXLS_HOST: "localhost"
  
  pxls-database:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: "pxls"
      POSTGRES_PASSWORD: "ChAnGeMeAtYoUrEaRlIeStCoNvEnIeNcE"
      POSTGRES_DB: "pxls"
